services:
  app:
    image: coretteket/prikkert:latest
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - '3000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - prikkert
      - traefik
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prikkert.rule=Host(`prikkert.nl`)'
      - 'traefik.http.routers.prikkert.entrypoints=websecure'
      - 'traefik.http.routers.prikkert.tls.certresolver=myresolver'
      - "traefik.http.routers.prikkert.middlewares=myratelimit@file,mycompress@file,myhsts@file,mysecurityheaders@file"

  db:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - '5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - prikkert
    restart: always

volumes:
  letsencrypt:
  db-data:

networks:
  prikkert:
  traefik:
    external: true
