services:
  app:
    image: coretteket/prikkert:latest
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        GITHUB_REPO: ${GITHUB_REPO}
        GITHUB_PAT: ${GITHUB_PAT}
    ports:
      - '3000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - prikkert
      - traefik
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prikkert.rule=Host(`prikkert.nl`)'
      - 'traefik.http.routers.prikkert.entrypoints=websecure'
      - 'traefik.http.routers.prikkert.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.prikkert.middlewares=myratelimit@file,mycompress@file,myhsts@file,mysecurityheaders@file'

  db:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - '5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - prikkert
    restart: always

  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    restart: always
    ports:
      - '4983'
    environment:
      - PORT=4983
      - STORE_PATH=/app
      - MASTERPASS=${DRIZZLE_GATEWAY_PASS}
    volumes:
      - drizzle-gateway:/app
    networks:
      - prikkert
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.drizzle-gateway.rule=Host(`db.prikkert.nl`)'
      - 'traefik.http.routers.drizzle-gateway.entrypoints=websecure'
      - 'traefik.http.routers.drizzle-gateway.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.drizzle-gateway.middlewares=myratelimit@file,mycompress@file,myhsts@file,mysecurityheaders@file'

volumes:
  letsencrypt:
  db-data:
  drizzle-gateway:

networks:
  prikkert:
  traefik:
    external: true
