services:
  app:
    image: coretteket/prikkert:latest
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 3000
    networks:
      - prikkert
      - traefik
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prikkert.rule=Host(`prikkert.nl`)'
      - 'traefik.http.routers.prikkert.entrypoints=websecure'
      - 'traefik.http.routers.prikkert.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.prikkert.middlewares=myratelimit@file,mycompress@file,myhsts@file,mysecurityheaders@file'

  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - prikkert
    restart: unless-stopped

volumes:
  db-data:

networks:
  prikkert:
  traefik:
    external: true
