FROM node:24-alpine AS node-corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

FROM node-corepack AS builder
WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .
RUN pnpm run sync
RUN pnpm run build
RUN pnpm prune --production

FROM node:24-alpine AS runtime
WORKDIR /app

COPY --from=builder --chown=node:node /app/build build/
COPY --from=builder --chown=node:node /app/node_modules node_modules/

COPY --chown=node:node package.json .
COPY --chown=node:node drizzle.config.ts .
COPY --chown=node:node ./src/lib/server/db ./src/lib/server/db
COPY --chown=node:node ./src/lib/server/crypto.ts ./src/lib/server/crypto.ts

USER node
ENV NODE_ENV=production
CMD ["node", "build"]
