FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN corepack prepare pnpm@10.0.0 --activate
RUN corepack pnpm install --frozen-lockfile
COPY . .
RUN corepack pnpm run build
RUN corepack pnpm prune --production

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
COPY drizzle.config.ts .
COPY ./src/lib/server/db ./src/lib/server/db
ENV NODE_ENV=production
CMD node build

