FROM node:22-alpine AS builder
WORKDIR /app
RUN npm install -g corepack@latest
COPY package.json pnpm-lock.yaml ./
RUN corepack pnpm install --frozen-lockfile
COPY . .
RUN corepack pnpm run build
RUN corepack pnpm prune --production

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
COPY drizzle.config.ts .
COPY ./src/lib/server/db ./src/lib/server/db
COPY ./src/lib/server/crypto.ts ./src/lib/server/crypto.ts
ENV NODE_ENV=production
CMD ["node", "build"]

